name: 'build'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:

  job-firmware:
    name: 'build firmware'
    runs-on: ubuntu-20.04
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'install packages'
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: 'compile firmware'
        run: bash ./.github/auto_build.sh

      - name: 'release assets'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: freedmo-firmware-all-*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true



